sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:

    # backend
    - stage: build
      install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./docker/install-aws.sh
        - aws s3 cp s3://tsmean-credentials/production."$PROD_CREDENTIALS".properties.json backend/properties/production.properties.json
        - docker build -t tsmean/server:"$TRAVIS_BUILD_NUMBER" -f docker/server.dockerfile .
        - docker push tsmean/server:"$TRAVIS_BUILD_NUMBER"
      script:
      - echo "everything a ok with backend build"

    - stage: test
      script:
      - echo "no backend tests yet"

    - stage: deploy
      install:
        - ./docker/install-aws.sh
        - aws ssm describe-instance-information
        - aws ssm send-command --instance-ids "i-0ed7d2d2191c0c2d5" --document-name "AWS-RunShellScript" --parameters commands=["export TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER && wget --no-cache https://raw.githubusercontent.com/tsmean/tsmean/"$TRAVIS_BRANCH"/docker/docker-compose.yml && docker stack deploy --compose-file docker-compose.yml tsmean && rm docker-compose.yml"] > docker/last-command.json
        - node docker/wait-for-aws-ssm.js
      script:
      - echo "backend deployment a-ok"

    # frontend
    - stage: build
      install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t tsmean/client:"$TRAVIS_BUILD_NUMBER" -f docker/client.dockerfile .
        - docker push tsmean/client:"$TRAVIS_BUILD_NUMBER"

        # TODO: REMOVE WHEN DOCKERIZED BUILD READY
        - cd shared
        - npm install
        - cd ../frontend
        - npm install
        - npm run build:prod
        - cd ..
        - ./docker/install-aws.sh
        - aws configure set preview.cloudfront true
        - aws s3 cp frontend/dist s3://demo.tsmean.com/ --recursive
        - aws cloudfront create-invalidation --distribution-id E194UGLQ78RUJV --paths "/*"
      script:
      - echo "everything ok with frontend build"

    - stage: test
      script:
      - echo "no frontend tests yet"

    - stage: deploy
      install:
        # TODO: GET DIST FOLDER FROM DOCKER IMAGE
#        - ./docker/install-aws.sh
#        - aws configure set preview.cloudfront true
#        - aws s3 cp frontend/dist s3://demo.tsmean.com/ --recursive
#        - aws cloudfront create-invalidation --distribution-id E194UGLQ78RUJV --paths "/*"
        - echo "temp disabled"
      script:
      - echo "frontent deployment a-ok"
